server:
  port: 8888

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.xiaogangkui.entity
  mapperLocations: classpath:mapper/*.xml
  typeHandlersPackage: com.xiaogangkui.dao

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/obas?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #初始化连接池的大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800

#  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content: type=text/html
#    cache: false
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
#  redis:
#    host: 192.168.102.246
#    password:
#    port: 6379
#    timeout: 3000
#    pool:
#      # 连接池中的最大空闲连接，默认值也是8。
#      max-idle: 500
#      #连接池中的最小空闲连接，默认值也是0。
#      min-idle: 50
#      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
#      max-active: 2000
#      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
#      max-wait: 3000
#      哨兵模式
#    sentinel:
#      master: master8026
#      nodes: 10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378