server:
  port: 8888
#  Actuator
management:
  endpoints:
    prometheus:
      id: springmetrics
    web:
      exposure:
        include: '*'
  metrics:
    export:
      show-prometheus:
        enabled: true
        step: 1m
        descriptions: true
  web:
    server:
      auto-time-requests: true
  server:
    port: 9999
  security:
    enabled: false
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR_ADMIN

info:
  head: head
  body: body
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.xiaogangkui.entity
  mapperLocations: classpath:mapper/*.xml
  typeHandlersPackage: com.xiaogangkui.dao

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cantaloupe?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowNativePasswords=true
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #初始化连接池的大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      #开启poolPreparedStatements后生效
      max-pool-prepared-statement-per-connection-size: 20
      #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置日志输出
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

#  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content: type=text/html
#    cache: false
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 3000
    pool:
      # 连接池中的最大空闲连接，默认值也是8。
      max-idle: 500
      #连接池中的最小空闲连接，默认值也是0。
      min-idle: 50
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-active: 2000
      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: 3000
#      哨兵模式
#    sentinel:
#      master: master8026
#      nodes: 10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378